"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPForwardGVNS,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPForwardGVNS class >> maxLength [
	^24

]

{ #category : #field }
ISUPForwardGVNS class >> octalLength [
	^3

]

{ #category : #field }
ISUPForwardGVNS class >> parameterName [
	^'Forward GVNS'

]

{ #category : #field }
ISUPForwardGVNS class >> parameterValue [
	^ISUPConstants parForwardGVNS

]

{ #category : #field }
ISUPForwardGVNS class >> spec [
	^'3.66'

]
