"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPCCSS,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPCCSS class >> maxLength [
	^nil

]

{ #category : #field }
ISUPCCSS class >> octalLength [
	^1

]

{ #category : #field }
ISUPCCSS class >> parameterName [
	^'CCSS'

]

{ #category : #field }
ISUPCCSS class >> parameterValue [
	^ISUPConstants parCCSS

]

{ #category : #field }
ISUPCCSS class >> spec [
	^'3.63'

]
