"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPGenericReference,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPGenericReference class >> maxLength [
	^nil

]

{ #category : #field }
ISUPGenericReference class >> octalLength [
	^3

]

{ #category : #field }
ISUPGenericReference class >> parameterName [
	^'Generic reference'

]

{ #category : #field }
ISUPGenericReference class >> parameterValue [
	^ISUPConstants parGenericReference

]

{ #category : #field }
ISUPGenericReference class >> spec [
	^'3.27'

]
