"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPConferenceTreatmentIndicators,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPConferenceTreatmentIndicators class >> maxLength [
	^nil

]

{ #category : #field }
ISUPConferenceTreatmentIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPConferenceTreatmentIndicators class >> parameterName [
	^'Conference treatment indicators'

]

{ #category : #field }
ISUPConferenceTreatmentIndicators class >> parameterValue [
	^ISUPConstants parConferenceTreatmentIndicators

]

{ #category : #field }
ISUPConferenceTreatmentIndicators class >> spec [
	^'3.76'

]
