"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPCallDiversionTreatmentIndicators,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPCallDiversionTreatmentIndicators class >> maxLength [
	^nil

]

{ #category : #field }
ISUPCallDiversionTreatmentIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPCallDiversionTreatmentIndicators class >> parameterName [
	^'Call diversion treatment indicators'

]

{ #category : #field }
ISUPCallDiversionTreatmentIndicators class >> parameterValue [
	^ISUPConstants parCallDiversionTreatmentIndicators

]

{ #category : #field }
ISUPCallDiversionTreatmentIndicators class >> spec [
	^'3.72'

]
