"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPDisplayInformation,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPDisplayInformation class >> maxLength [
	^nil

]

{ #category : #field }
ISUPDisplayInformation class >> octalLength [
	^1

]

{ #category : #field }
ISUPDisplayInformation class >> parameterName [
	^'Display information'

]

{ #category : #field }
ISUPDisplayInformation class >> parameterValue [
	^ISUPConstants parDisplayInformation

]

{ #category : #field }
ISUPDisplayInformation class >> spec [
	^'3.77'

]
