"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPOriginalCalledINNumber,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPOriginalCalledINNumber class >> maxLength [
	^nil

]

{ #category : #field }
ISUPOriginalCalledINNumber class >> octalLength [
	^2

]

{ #category : #field }
ISUPOriginalCalledINNumber class >> parameterName [
	^'Original called IN number'

]

{ #category : #field }
ISUPOriginalCalledINNumber class >> parameterValue [
	^ISUPConstants parOriginalCalledINNumber

]

{ #category : #field }
ISUPOriginalCalledINNumber class >> spec [
	^'3.87'

]
