"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPRemoteOperations,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPRemoteOperations class >> maxLength [
	^nil

]

{ #category : #field }
ISUPRemoteOperations class >> octalLength [
	^6

]

{ #category : #field }
ISUPRemoteOperations class >> parameterName [
	^'Remote operations'

]

{ #category : #field }
ISUPRemoteOperations class >> parameterValue [
	^ISUPConstants parRemoteOperations

]

{ #category : #field }
ISUPRemoteOperations class >> spec [
	^'3.48'

]
