"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPUserServiceInformationPrime,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPUserServiceInformationPrime class >> maxLength [
	^11

]

{ #category : #field }
ISUPUserServiceInformationPrime class >> octalLength [
	^2

]

{ #category : #field }
ISUPUserServiceInformationPrime class >> parameterName [
	^'User service information prime'

]

{ #category : #field }
ISUPUserServiceInformationPrime class >> parameterValue [
	^ISUPConstants parUserServiceInformationPrime

]

{ #category : #field }
ISUPUserServiceInformationPrime class >> spec [
	^'3.58'

]
