"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPUserToUserInformation,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPUserToUserInformation class >> maxLength [
	^129

]

{ #category : #field }
ISUPUserToUserInformation class >> octalLength [
	^1

]

{ #category : #field }
ISUPUserToUserInformation class >> parameterName [
	^'User-to-user information'

]

{ #category : #field }
ISUPUserToUserInformation class >> parameterValue [
	^ISUPConstants parUserToUserInformation

]

{ #category : #field }
ISUPUserToUserInformation class >> spec [
	^'3.61'

]
