"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPCallOfferingTreatmentIndicators,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPCallOfferingTreatmentIndicators class >> maxLength [
	^nil

]

{ #category : #field }
ISUPCallOfferingTreatmentIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPCallOfferingTreatmentIndicators class >> parameterName [
	^'Call offering treatment indicators'

]

{ #category : #field }
ISUPCallOfferingTreatmentIndicators class >> parameterValue [
	^ISUPConstants parCallOfferingTreatmentIndicators

]

{ #category : #field }
ISUPCallOfferingTreatmentIndicators class >> spec [
	^'3.74'

]
