"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPCircuitAssignmentMap,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPCircuitAssignmentMap class >> maxLength [
	^5

]

{ #category : #field }
ISUPCircuitAssignmentMap class >> octalLength [
	^4

]

{ #category : #field }
ISUPCircuitAssignmentMap class >> parameterName [
	^'Circuit assignment map'

]

{ #category : #field }
ISUPCircuitAssignmentMap class >> parameterValue [
	^ISUPConstants parCircuitAssignmentMap

]

{ #category : #field }
ISUPCircuitAssignmentMap class >> spec [
	^'3.69'

]
