"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPNetworkManagementControls,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPNetworkManagementControls class >> maxLength [
	^nil

]

{ #category : #field }
ISUPNetworkManagementControls class >> octalLength [
	^1

]

{ #category : #field }
ISUPNetworkManagementControls class >> parameterName [
	^'Network management controls'

]

{ #category : #field }
ISUPNetworkManagementControls class >> parameterValue [
	^ISUPConstants parNetworkManagementControls

]

{ #category : #field }
ISUPNetworkManagementControls class >> spec [
	^'3.68'

]
