"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPPivotRoutingBackwardInformation,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPPivotRoutingBackwardInformation class >> maxLength [
	^nil

]

{ #category : #field }
ISUPPivotRoutingBackwardInformation class >> octalLength [
	^1

]

{ #category : #field }
ISUPPivotRoutingBackwardInformation class >> parameterName [
	^'Pivot routing backward information'

]

{ #category : #field }
ISUPPivotRoutingBackwardInformation class >> parameterValue [
	^ISUPConstants parPivotRoutingBackwardInformation

]

{ #category : #field }
ISUPPivotRoutingBackwardInformation class >> spec [
	^'3.95'

]
