"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPUIDActionIndicators,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPUIDActionIndicators class >> maxLength [
	^nil

]

{ #category : #field }
ISUPUIDActionIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPUIDActionIndicators class >> parameterName [
	^'UID action indicators'

]

{ #category : #field }
ISUPUIDActionIndicators class >> parameterValue [
	^ISUPConstants parUIDActionIndicators

]

{ #category : #field }
ISUPUIDActionIndicators class >> spec [
	^'3.78'

]
