"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPSubsequentNumber,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPSubsequentNumber class >> maxLength [
	^nil

]

{ #category : #field }
ISUPSubsequentNumber class >> octalLength [
	^2

]

{ #category : #field }
ISUPSubsequentNumber class >> parameterName [
	^'Subsequent number'

]

{ #category : #field }
ISUPSubsequentNumber class >> parameterValue [
	^ISUPConstants parSubsequentNumber

]

{ #category : #field }
ISUPSubsequentNumber class >> spec [
	^'3.51'

]
