"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPBackwardGVNS,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPBackwardGVNS class >> maxLength [
	^nil

]

{ #category : #field }
ISUPBackwardGVNS class >> octalLength [
	^1

]

{ #category : #field }
ISUPBackwardGVNS class >> parameterName [
	^'Backward GVNS'

]

{ #category : #field }
ISUPBackwardGVNS class >> parameterValue [
	^ISUPConstants parBackwardGVNS

]

{ #category : #field }
ISUPBackwardGVNS class >> spec [
	^'3.62'

]
