"
I am an auto generated ISUP fixed field.
"
Class {
	#name : #ISUPPivotCapability,
	#superclass : #MSGFixedField,
	#category : #ISUP
}

{ #category : #field }
ISUPPivotCapability class >> octalLength [
	^1

]

{ #category : #field }
ISUPPivotCapability class >> parameterName [
	^'Pivot capability'

]

{ #category : #field }
ISUPPivotCapability class >> parameterValue [
	^ISUPConstants parPivotCapability

]

{ #category : #field }
ISUPPivotCapability class >> spec [
	^'3.84'

]
