"
I am an auto generated ISUP fixed field.
"
Class {
	#name : #ISUPPivotRoutingIndicators,
	#superclass : #MSGFixedField,
	#category : #ISUP
}

{ #category : #field }
ISUPPivotRoutingIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPPivotRoutingIndicators class >> parameterName [
	^'Pivot routing indicators'

]

{ #category : #field }
ISUPPivotRoutingIndicators class >> parameterValue [
	^ISUPConstants parPivotRoutingIndicators

]

{ #category : #field }
ISUPPivotRoutingIndicators class >> spec [
	^'3.85'

]
