"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPPivotRoutingForwardInformation,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPPivotRoutingForwardInformation class >> maxLength [
	^nil

]

{ #category : #field }
ISUPPivotRoutingForwardInformation class >> octalLength [
	^1

]

{ #category : #field }
ISUPPivotRoutingForwardInformation class >> parameterName [
	^'Pivot routing forward information'

]

{ #category : #field }
ISUPPivotRoutingForwardInformation class >> parameterValue [
	^ISUPConstants parPivotRoutingForwardInformation

]

{ #category : #field }
ISUPPivotRoutingForwardInformation class >> spec [
	^'3.94'

]
