"
I am an auto generated ISUP fixed field.
"
Class {
	#name : #ISUPPivotCounter,
	#superclass : #MSGFixedField,
	#category : #ISUP
}

{ #category : #field }
ISUPPivotCounter class >> octalLength [
	^1

]

{ #category : #field }
ISUPPivotCounter class >> parameterName [
	^'Pivot counter'

]

{ #category : #field }
ISUPPivotCounter class >> parameterValue [
	^ISUPConstants parPivotCounter

]

{ #category : #field }
ISUPPivotCounter class >> spec [
	^'3.93'

]
