"
I am an auto generated ISUP variable.
"
Class {
	#name : #ISUPUIDCapabilityIndicators,
	#superclass : #MSGVariableField,
	#category : #ISUP
}

{ #category : #field }
ISUPUIDCapabilityIndicators class >> maxLength [
	^nil

]

{ #category : #field }
ISUPUIDCapabilityIndicators class >> octalLength [
	^1

]

{ #category : #field }
ISUPUIDCapabilityIndicators class >> parameterName [
	^'UID capability indicators'

]

{ #category : #field }
ISUPUIDCapabilityIndicators class >> parameterValue [
	^ISUPConstants parUIDCapabilityIndicators

]

{ #category : #field }
ISUPUIDCapabilityIndicators class >> spec [
	^'3.79'

]
