"
I am an auto generated ISUP fixed field.
"
Class {
	#name : #ISUPTransmissionMediumRequirementPrime,
	#superclass : #MSGFixedField,
	#category : #ISUP
}

{ #category : #field }
ISUPTransmissionMediumRequirementPrime class >> octalLength [
	^1

]

{ #category : #field }
ISUPTransmissionMediumRequirementPrime class >> parameterName [
	^'Transmission medium requirement prime'

]

{ #category : #field }
ISUPTransmissionMediumRequirementPrime class >> parameterValue [
	^ISUPConstants parTransmissionMediumRequirementPrime

]

{ #category : #field }
ISUPTransmissionMediumRequirementPrime class >> spec [
	^'3.55'

]
